Revert "Ensuring we can handle IDNs without issues (#936)"
This reverts commit 83089d6e311098dcf5a1d08d6bb0c00874b9a4b2 because it
turns out we don't correctly support IDNs in all cases.

See

```
2020/09/11 23:33:17 debug resolve dns.google.com...
2020/09/11 23:33:17 debug resolve dns.google.com... ([8.8.4.4 8.8.8.8 2001:4860:4860::8888 2001:4860:4860::8844], <nil>) in 44.150342ms
2020/09/11 23:33:17 debug resolve яндекс.рф...
2020/09/11 23:33:17 debug resolve яндекс.рф... ([77.88.55.66 5.255.255.55 5.255.255.5 77.88.55.55 2a02:6b8:a::a], <nil>) in 1.852079ms
2020/09/11 23:33:17 debug resolve dns.google.com...
2020/09/11 23:33:17 debug resolve dns.google.com... ([8.8.4.4 8.8.8.8 2001:4860:4860::8844 2001:4860:4860::8888], <nil>) in 73.81118ms
2020/09/11 23:33:17 debug resolve яндекс.рф...
2020/09/11 23:33:17 debug resolve яндекс.рф... ([], dns: domain must be fully qualified) in 50.781µs
--- FAIL: TestIntegrationNewResolverUDPAddress (0.07s)
    integration_test.go:48: dns: domain must be fully qualified
```

We need to work for more time on this patch.